---
- name: Install and configure Zabbix on AlmaLinux
  hosts: almalinux_vm
  become: yes
  vars:
    zabbix_version: "7.0.3"  # Setze hier die gewünschte Zabbix-Version ein
    zabbix_db_name: "zabbix"
    zabbix_db_user: "zabbix"
    zabbix_db_password: "password"
    zabbix_server_ip: "127.0.0.1"  # Hier kann die IPv4 oder IPv6 Adresse des Zabbix-Servers eingetragen werden

  tasks:

    - name: Install EPEL repository
      yum:
        name: epel-release
        state: present

    - name: Add Zabbix repository
      yum:
        name: "https://repo.zabbix.com/zabbix/7.0/rhel/8/x86_64/zabbix-release-7.0.3-1.el8.noarch.rpm"
        state: present

    - name: Install Zabbix server, frontend, agent and mariadb
      yum:
        name:
          - zabbix-server-mysql
          - zabbix-agent
          - zabbix-web-mysql
          - zabbix-apache-conf
          - mariadb-server
          - mariadb
          - httpd
          - php-mbstring
          - php-gd
          - php-xml
          - php-bcmath
        state: present

    - name: Start and enable MariaDB service
      systemd:
        name: mariadb
        state: started
        enabled: yes

    - name: Create Zabbix database
      mysql_db:
        name: "zabbix"
        state: present
        login_user: root

    - name: Create Zabbix database user
      mysql_user:
        name: "zabbix"
        password: "zabbix"
        priv: "zabbix.*:ALL"
        host: "localhost"
        state: present
        login_user: root

    - name: Import initial Zabbix schema
      command: >
        mysql -u zabbix -p password zabbix < /usr/share/doc/zabbix-server-mysql*/create.sql
      args:
        creates: "/usr/share/doc/zabbix-server-mysql*/create.sql"

    - name: Configure Zabbix server database settings
      lineinfile:
        path: /etc/zabbix/zabbix_server.conf
        regexp: "^#? DBPassword="
        line: "DBPassword=password"
        state: present

    - name: Start and enable Zabbix server
      systemd:
        name: zabbix-server
        state: started
        enabled: yes

    - name: Start and enable Zabbix agent
      systemd:
        name: zabbix-agent
        state: started
        enabled: yes

    - name: Configure PHP timezone for Zabbix frontend
      lineinfile:
        path: /etc/php-fpm.d/zabbix.conf
        regexp: "^;?php_value\\[date.timezone\\]"
        line: "php_value[date.timezone] = Europe/Berlin"
        state: present

    - name: Restart PHP-FPM service
      systemd:
        name: php-fpm
        state: restarted

    - name: Start and enable Apache HTTP server
      systemd:
        name: httpd
        state: started
        enabled: yes

    - name: Open HTTP port for Zabbix frontend
      firewalld:
        port: 80/tcp
        permanent: yes
        state: enabled
        immediate: yes

    - name: Reload firewall to apply changes
      firewalld:
        state: reloaded
