---
- hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required dependencies
      apt:
        name:
          - apt-transport-https
          - software-properties-common
        state: present

    - name: Add Zabbix repository
      apt_repository:
        repo: "deb http://repo.zabbix.com/zabbix/5.0/ubuntu bionic main"
        state: present

    - name: Add Zabbix public key
      apt_key:
        url: "https://repo.zabbix.com/zabbix-official-repo.key"
        state: present

    - name: Install Zabbix server, frontend, agent
      apt:
        name:
          - zabbix-server-mysql
          - zabbix-frontend-php
          - zabbix-agent
        state: present

    - name: Start and enable Zabbix server
      service:
        name: zabbix-server
        enabled: yes
        state: started

    - name: Start and enable Zabbix agent
      service:
        name: zabbix-agent
        enabled: yes
        state: started