name: Terraform Proxmox Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform Deployment'
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.0

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Apply
        id: apply
        env:
          TF_VAR_proxmox_url: ${{ secrets.PROXMOX_URL }}
          TF_VAR_proxmox_user: ${{ secrets.PROXMOX_USER }}
          TF_VAR_proxmox_password: ${{ secrets.PROXMOX_PASS }}
        run: terraform apply -auto-approve
        working-directory: ./terraform