name: Terraform Azure Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform Deployment'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.0

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Apply
        id: apply
        env:
          TF_VAR_admin_password: ${{ secrets.AZURE_VM_ADMIN_PASSWORD }}
        run: terraform apply -auto-approve
        working-directory: ./terraform

      - name: Output VM Public IP
        run: |
          VM_IP=$(terraform output -raw vm_public_ip)
          echo "VM IP: $VM_IP"
        working-directory: ./terraform
